[[redirects]]
  from = "/api/*"
  to = "https://api.coingecko.com/api/v3/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
